/* =========================================================
   INSY7213 PRACTICAL ASSIGNMENT 1
   QUESTION 5
   CHEETAH DELIVERIES

   STUDENT NUMBER: ST10440597
   ========================================================= */
   /* =========================================================
   QUESTION 5.1

   The Operations Manager requires a report showing the
   staff member who processed the highest number of
   deliveries.

   The STAFF table identifies the employee.
   DELIVERY_ITEMS identifies which staff member processed
   each delivery item.
   DRIVER_DELIVERIES identifies the actual delivery records.

   Therefore, DRIVER_DELIVERIES is counted to determine
   how many deliveries each staff member processed.
   ========================================================= */

SET SERVEROUTPUT ON;

DECLARE

    /* Cursor retrieves staff members and counts the actual
       delivery records associated with each staff member. */
    CURSOR top_staff_cursor IS
        SELECT
            s.STAFF_ID,
            s.FIRST_NAME,
            s.SURNAME,
            COUNT(dd.DRIVER_DELIVERY_ID) AS DELIVERY_COUNT
        FROM STAFF s
        JOIN DELIVERY_ITEMS di
            ON s.STAFF_ID = di.STAFF_ID
        JOIN DRIVER_DELIVERIES dd
            ON di.DELIVERY_ITEM = dd.DELIVERY_ITEM_ID
        GROUP BY
            s.STAFF_ID,
            s.FIRST_NAME,
            s.SURNAME
        ORDER BY
            COUNT(dd.DRIVER_DELIVERY_ID) DESC;

    /* Variables store the staff information retrieved
       from the cursor. */
    v_staff_id STAFF.STAFF_ID%TYPE;
    v_first_name STAFF.FIRST_NAME%TYPE;
    v_surname STAFF.SURNAME%TYPE;
    v_delivery_count NUMBER;

BEGIN

    /* Open the cursor containing the delivery totals. */
    OPEN top_staff_cursor;

    /* Only the first record is required because the cursor
       is ordered from the highest delivery count to lowest. */
    FETCH top_staff_cursor
    INTO
        v_staff_id,
        v_first_name,
        v_surname,
        v_delivery_count;

    /* Check that a record was successfully retrieved. */
    IF top_staff_cursor%FOUND THEN

        DBMS_OUTPUT.PUT_LINE(
            '----------------------------------------'
        );

        DBMS_OUTPUT.PUT_LINE(
            'STAFF ID: ' || v_staff_id
        );

        DBMS_OUTPUT.PUT_LINE(
            'FIRST NAME: ' || v_first_name
        );

        DBMS_OUTPUT.PUT_LINE(
            'SURNAME: ' || v_surname
        );

        DBMS_OUTPUT.PUT_LINE(
            'DELIVERIES PROCESSED: ' || v_delivery_count
        );

        DBMS_OUTPUT.PUT_LINE(
            '----------------------------------------'
        );

    ELSE

        DBMS_OUTPUT.PUT_LINE(
            'No delivery information was found.'
        );

    END IF;

    /* Close the cursor after the report has been produced. */
    CLOSE top_staff_cursor;

EXCEPTION

    /* Handles any unexpected error and ensures that
       a useful message is displayed. */
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE(
            'An unexpected error occurred: ' || SQLERRM
        );

END;
/ 
 /* =========================================================
   QUESTION 5.3.2

   CREATE A MANAGEMENT VIEW

   This View combines staff information with delivery
   information and calculates how many actual deliveries
   each staff member has processed.

   Management does not need to understand the underlying
   table joins. They can use the View as though it were
   a simple table.
   ========================================================= */

CREATE OR REPLACE VIEW V_STAFF_DELIVERY_REPORT AS
SELECT
    s.STAFF_ID,
    s.FIRST_NAME,
    s.SURNAME,
    COUNT(dd.DRIVER_DELIVERY_ID) AS DELIVERIES_PROCESSED
FROM STAFF s
JOIN DELIVERY_ITEMS di
    ON s.STAFF_ID = di.STAFF_ID
JOIN DRIVER_DELIVERIES dd
    ON di.DELIVERY_ITEM = dd.DELIVERY_ITEM_ID
GROUP BY
    s.STAFF_ID,
    s.FIRST_NAME,
    s.SURNAME;
    /* Display the information generated by the management View. */

SELECT *
FROM V_STAFF_DELIVERY_REPORT
ORDER BY DELIVERIES_PROCESSED DESC;